#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
Thermod monitor for Raspberry Pi with one button and one RGB LED.

@author:     Simone Rossetto
@copyright:  2018 Simone Rossetto
@license:    GNU General Public License v3
@contact:    simros85@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import signal
import argparse
import requests
import time
import logging
import sys

from thermod import ThermodStatus
from thermod import MAIN_CONFIG_FILES as THERMOD_CONFIG_FILES
from thermod.common import LogStyleAdapter, LOGGER_BASE_NAME, LOGGER_FMT_MSG, \
    LOGGER_FMT_TIME, LOGGER_FMT_STYLE, LOGGER_FMT_MSG_SYSLOG, \
    LOGGER_FMT_DATETIME, SOCKET_DEFAULT_HOST, SOCKET_DEFAULT_PORT, \
    RET_CODE_OK, RET_CODE_CFG_FILE_UNKNOWN_ERR, RET_CODE_CFG_FILE_INVALID
from gpiozero import Button, RGBLED
from threading import Timer, Lock
from logging.handlers import SysLogHandler
from operator import mul

__version__ = '1.1.0.dev1'
__date__ = '2017-05-12'
__updated__ = '2020-05-08'

__monitor_name__ = 'buttonled'

# TODO find a way to stop an ongoing GET request when a SIGTERM is received
# TODO review colors in order to make them more "logical"


# setting up logging system
logger = LogStyleAdapter(logging.getLogger('{}.{}'.format(LOGGER_BASE_NAME, __monitor_name__)))
logger.setLevel(logging.INFO)

# config filename and search paths
MAIN_CONFIG_FILENAME = 'monitor-buttonled.conf'
MAIN_CONFIG_FILES = [os.path.join(os.path.expanduser('~/.thermod'), MAIN_CONFIG_FILENAME),
                     os.path.join(os.path.expanduser('~/.config/thermod'), MAIN_CONFIG_FILENAME),
                     os.path.join('/usr/local/etc/thermod', MAIN_CONFIG_FILENAME),
                     os.path.join('/var/lib/thermod', MAIN_CONFIG_FILENAME),
                     os.path.join('/etc/thermod', MAIN_CONFIG_FILENAME)]
MAIN_CONFIG_FILENAME.extend(THERMOD_CONFIG_FILES)

# default pins
PIN_RED = 17
PIN_GREEN = 27
PIN_BLUE = 22
PIN_BUTTON = 5

# default LED colors
LED_COLOR_BLACK = (0, 0, 0)
LED_COLOR_RED = (0.8, 0, 0)
LED_COLOR_YELLOW = (1, 1, 0)
LED_COLOR_GREEN = (0, 0.3, 0)
LED_COLOR_BLUE = (0, 0, 1)
LED_COLOR_CYAN = (0, 0.7, 1)
LED_COLOR_MAGENTA = (0.3, 0, 1)

# default values for brightness
LED_BRIGHTNESS = 1.0
NIGHT_BRIGHTNESS = 0.3
NIGHT_START_TIME = '21:00'
NIGHT_END_TIME = '07:00'

def get_color(status):
    """Convert a Thermod status to its corresponding LED color."""
    
    logger.debug('converting status with colour code')
    
    if status == 'auto':
        color = LED_COLOR_GREEN
    elif status == 'tmax':
        color = LED_COLOR_YELLOW
    elif status == 'tmin':
        color = LED_COLOR_CYAN
    elif status == 't0':
        color = LED_COLOR_BLUE
    elif status in ('on', 'off'):
        # The color for ON and OFF statues is the same, but in case of ON
        # it blinks because the heating is always on. Status ON cannot be
        # set with the button, so there is no possible error for user.
        color = LED_COLOR_RED
    else:
        raise ValueError('invalid status')
    
    return color

# the real monitor class
class ButtonLedMonitor(object):
    """Manage a Thermod monitor with an RGB LED and a push button."""
    
    def __init__(self, red, green, blue, button, host, port, timeout=3, brightness, night_brightness, night_start, night_end):
        """Init a ButtonLedMonitor with corresponding PINs.
        
        @param red pin number for red led
        @param green pin number for green led
        @param blue pin number for blue led
        @param button pin number for push button
        @param brightness default led brightness (float value between 0 and 1)
        @param night_brightness night time led brightness (float value between 0 and 1)
        @param night_start start time for night interval (integer value in format `HHMM`)
        @param night_end end time for night interval (integer value in format `HHMM`)
        """
        
        self._status = 'off'
        self._new_status = None
        
        self._pins = (red, green, blue, button)
        
        self._session = None
        self._request_url = 'http://{}:{}'.format(host, port)
        
        self._timeout = timeout
        self._timer = None
        
        self._lock = Lock()
        self._changing_status = Lock()
        self._press_id = 0
        
        self._bright = brightness
        self._nbright = night_brightness
        self._nstart = night_start
        self._nend = night_end
    
    def adjust_brightness(self, color):
        """Return the provided color with brightness adjusted."""
        now = int(time.strftime('%H%M'))
        brightness = self._nbright if (now >= self._nstart or now < self._nend) else self._bright
        return tuple(map(mul, color, (brightness, ) * 3))
    
    def __enter__(self):
        self._session = requests.Session()
        
        self._led = RGBLED(self._pins[0], self._pins[1], self._pins[2])
        self._button = Button(self._pins[3])
        
        self._led.blink(on_time=0.2,
                        off_time=0.2,
                        on_color=self.adjust_brightness(LED_COLOR_RED),
                        off_color=self.adjust_brightness(LED_COLOR_BLACK))
        
        self._button.when_pressed = self._manage_button_press
        return self
    
    def __exit__(self, exc_type=None, exc_value=None, traceback=None):
        self._session.close()
        
        if self._timer:
            self._timer.cancel()
            self._timer = None
        
        self._button.when_pressed = None
        self._button.close()
        
        self._led.off()
        self._led.close()
    
    def update_status(self, longpolling=True):
        try:
            logger.debug('{} Thermod status', ('longpolling' if longpolling else 'updating monitor with'))
            
            rsp = self._session.get('{}/{}'.format(
                self._request_url,
                ('monitor?name={}'.format(__monitor_name__) if longpolling else 'status')))
            
            rsp.raise_for_status()  # check error status code
            
            logger.debug('processing response data')
            jrsp = rsp.json()
            status = ThermodStatus(**jrsp)
            
            color = self.adjust_brightness(get_color(status.status))
            off_color = self.adjust_brightness(LED_COLOR_BLACK)
            
            with self._lock:
                logger.debug('updating LED colour')
                
                # If a change isn't happening (thus the lock is not acquired)
                # we update the led, otherwise we skip this step.
                if self._changing_status.acquire(blocking=False):
                    try:
                        if status.heating_status == 1:
                            self._led.off()
                            self._led.blink(on_time=0.5,
                                            off_time=0.5,
                                            on_color=color,
                                            off_color=off_color)
                        else:
                            self._led.color = color
                        
                        self._status = status.status
                    
                    finally:
                        self._changing_status.release()
        
        except Exception as e:
            self._led.off()
            self._led.blink(on_time=0.2,
                            off_time=0.2,
                            on_color=self.adjust_brightness(LED_COLOR_RED),
                            off_color=self.adjust_brightness(LED_COLOR_YELLOW))
            
            raise
    
    def _save_new_status(self, press_id):
        with self._lock:
            # If this is the last started Timer then update the status
            # otherwise do nothing.
            if press_id == self._press_id:
                logger.info('updating Thermod with new status "{}"', self._new_status)
                try:
                    self._led.off()
                    rsp = self._session.post('{}/settings'.format(self._request_url),
                                             data={'status': self._new_status})
                finally:
                    self._new_status = None
                    self._changing_status.release()
    
    def _manage_button_press(self):
        with self._lock:
            try:
                if self._changing_status.acquire(blocking=False):
                    logger.debug('button pressed for first time')
                    
                    # This is the first press, we check the current status and
                    # we update the temporary new status.
                    if self._status == 'auto':
                        self._new_status = 'tmax'
                    else:
                        self._new_status = 'auto'
                
                else:
                    logger.debug('button pressed')
                    
                    # This is a sequential press, we clear the timer, we check
                    # the temporary new status and we update itself.
                    if self._timer:
                        self._timer.cancel()
                        self._timer = None
                    
                    if self._new_status == 'auto':
                        self._new_status = 'tmax'
                    elif self._new_status == 'tmax':
                        self._new_status = 'off'
                    elif self._new_status == 'off':
                        self._new_status = 'tmin'
                    elif self._new_status == 'tmin':
                        self._new_status = 't0'
                    elif self._new_status == 't0':
                        self._new_status = 'auto'
                
                self._led.color = self.adjust_brightness(get_color(self._new_status))
            
            finally:
                self._press_id += 1
                self._timer = Timer(self._timeout, self._save_new_status, [self._press_id])
                self._timer.start()


# shutdown check and return code
running = True
main_return_code = 0

def shutdown(signum=None, frame=None, exitcode=0):
    global running, main_return_code
    logger.info('shutdown requested')
    running = False
    main_return_code = exitcode

signal.signal(signal.SIGTERM, shutdown)


# parse input arguments
parser = argparse.ArgumentParser(description='Thermod Button+LED Monitor')
parser.add_argument('-c', '--config', action='store', default=None, help='path to configuration file')
parser.add_argument('-L', '--log', action='store', default=None, help='write log messages to LOG file (full path)')
parser.add_argument('-D', '--debug', action='store_true', help='start the monitor in debug mode')
parser.add_argument('--daemon', action='store_true', help='log messages to syslog (useful if started by systemd)')
parser.add_argument('-v', '--version', action='version', version='%(prog)s {}'.format(__version__))
args = parser.parse_args()

# set logger
if args.debug:
    logger.setLevel(logging.DEBUG)

if args.daemon:
    syslog = SysLogHandler(address='/dev/log', facility=SysLogHandler.LOG_DAEMON)
    syslog.setFormatter(logging.Formatter(fmt=LOGGER_FMT_MSG_SYSLOG,
                                          style=LOGGER_FMT_STYLE))
    logger.addHandler(syslog)
else:
    console = logging.StreamHandler(sys.stdout)
    console.setFormatter(logging.Formatter(fmt=LOGGER_FMT_MSG,
                                           datefmt=LOGGER_FMT_TIME,
                                           style=LOGGER_FMT_STYLE))
    logger.addHandler(console)

if args.log:
    try:
        logfile = logging.FileHandler(args.log, mode='a')
    
    except PermissionError as pe:
        logger.warning('cannot write log to `{}`: {}', args.log, pe)
        logger.info('the monitor will start without logfile')
    
    else:
        logfile.setFormatter(logging.Formatter(fmt=LOGGER_FMT_MSG,
                                               datefmt=LOGGER_FMT_DATETIME,
                                               style=LOGGER_FMT_STYLE))
        logger.addHandler(logfile)
    
        if args.daemon:
            # When a custom log file is configured and the deamon in started
            # in background, only warnings and errors are printed to syslog.
            syslog.setLevel(logging.WARNING)
        
        logger.debug('logging to file {}', args.log)

# read config file
config_files = args.config if args.config else MAIN_CONFIG_FILES

try:
    cfg_err = RET_CODE_OK
    cfg = configparser.ConfigParser()
    logger.debug('searching configuration in files {}', config_files)
    
    _cfg_files_found = cfg.read(config_files)
    
    if _cfg_files_found:
        logger.debug('configuration files found: {}', _cfg_files_found)
    else:
        raise FileNotFoundError()
   
   # pins
   red = cfg.getint('monitor/buttonled', 'red', PIN_RED)
   green = cfg.getint('monitor/buttonled', 'green', PIN_GREEN)
   blue = cfg.getint('monitor/buttonled', 'blue', PIN_BLUE)
   button = cfg.getint('monitor/buttonled', 'button', PIN_BUTTON)
   
   # connection settings (searched even in main thermod settings)
   host = cfg.get('monitor/buttonled', 'host', cfg.get('socket', 'host', SOCKET_DEFAULT_HOST))
   port = cfg.getint('monitor/buttonled', 'port', cfg.get('socket', 'port', SOCKET_DEFAULT_PORT))
   
   # LED brightness normal and night time
   led_brightness = cfg.getfloat('monitor/buttonled', 'led-brightness', LED_BRIGHTNESS)
   night_brightness = cfg.getfloat('monitor/buttonled', 'night-brightness', NIGHT_BRIGHTNESS)
   night_start_time = int(cfg.get('monitor/buttonled', 'night-start', NIGHT_START_TIME).replace(':', ''))
   night_end_time = int(cfg.get('monitor/buttonled', 'night-stop', NIGHT_END_TIME).replace(':', ''))

except ValueError as ve:
    logger.error('invalid value in configuration file: {}', ve)
    cfe_error = RET_CODE_CFG_FILE_INVALID

except configparser.Error as cpe:
    logger.critical('error in configuration file: {}', cpe)
    cfg_err = RET_CODE_CFG_FILE_INVALID

except FileNotFoundError:
    logger.info('no configuration files found, continue with default settings')

except Exception as e:
    logger.critical('unknown error in configuration file: {}', e)
    cfg_err = RET_CODE_CFG_FILE_UNKNOWN_ERR

finally:
    if cfg_err != RET_CODE_OK:
        logger.info('closing monitor with return code {}', cfg_err)
        exit(cfg_err)

# main
with ButtonLedMonitor(red, green, blue, button, host, port) as monitor:
    try:
        logger.info('Thermod Button+LED monitor v{} started', __version__)
        
        try:
            logger.debug('start first connection to Thermod')
            monitor.update_status(False)
        
        except (requests.ConnectionError, requests.Timeout) as e:
            # do nothing, continue and go to sleep
            logger.error('errore while connecting to Thermod: {}', e)
        
        logger.debug('starting main cycle')
        
        while running:
            try:
                monitor.update_status()
            
            except ValueError as ve:
                logger.warning('invalid value returned from Thermod: {}', ve)
            
            except requests.RequestException as e:
                logger.warning('error while communicating with Thermod: {}', e)
                time.sleep(10)
    
    except Exception as e:
        logger.critical('unknown error: {}', e)
        main_return_code = 1
    
    except KeyboardInterrupt:
        logger.debug('shutdown requested by keyboard interrupt')
        shutdown()

logger.info('closing monitor with return code {}', main_return_code)
exit(main_return_code)

# vim: syntax=python fileencoding=utf-8
